FROM python:3.10

COPY ./ ./app/
WORKDIR /app
RUN pip install poetry==1.5.1
RUN poetry install

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["poetry","run"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8501", "--reload"]
